Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: download_reports.handler
      CodeUri: C:\Users\rasny\projects\step_functions
      Runtime: python3.8
      Architectures:
        - x86_64